
services:

    wordpress:
        image:                          wordpress:6.7
        container_name:                 mi-wordpress
        volumes:
                                      - /home/ubuntu/environment/datos/wordpress:/var/www/html
        environment:
              WORDPRESS_DB_PASSWORD:    password
              WORDPRESS_DB_USER:        usuario
              WORDPRESS_DB_NAME:        bd
              WORDPRESS_DB_HOST:        mariadb
        ports:
                                      - 8081:80

    mariadb: # fqdn (nombre de red del contenedor)
        image:                          mariadb:11.7
        container_name:                 mi-mariadb
        volumes:
                                      - /home/ubuntu/environment/datos/bd:/var/lib/mysql
        environment:
              MARIADB_ROOT_PASSWORD:    password
              MARIADB_PASSWORD:         password
              MARIADB_USER:             usuario
              MARIADB_DATABASE:         bd

    adminer:
        image:                          adminer:5.0.6
        container_name:                 mi-adminer
        ports:
                                      - 8080:8080


                            # lista ordenada de textos con los nombres de variables separados de los valores por un signo igual
                              #- MARIADB_ROOT_PASSWORD=password
                              #- MARIADB_PASSWORD=password
                              #- MARIADB_USER=usuario
                              #- MARIADB_DATABASE=bd
                            # mapa de textos
