
kind:                 ConfigMap # Valores que se identifican con una clave y se pueden usar en los pods
                                # Para varias cosas, entre ellas para rellenar variables de entorno
apiVersion:           v1

metadata:
  name:               datos-mariadb

usuario:              usuario
nombre_bbdd:          bd

---

kind:                 ConfigMap 
apiVersion:           v1

metadata:
  name:               configuracion_bbdd

mariadb.cnf: |
  # The MariaDB configuration file
  #
  # The MariaDB/MySQL tools read configuration files in the following order:
  # 0. "/etc/mysql/my.cnf" symlinks to this file, reason why all the rest is read.
  # 1. "/etc/mysql/mariadb.cnf" (this file) to set global defaults,
  # 2. "/etc/mysql/conf.d/*.cnf" to set global options.
  # 3. "/etc/mysql/mariadb.conf.d/*.cnf" to set MariaDB-only options.
  # 4. "~/.my.cnf" to set user-specific options.
  #
  # If the same option is defined multiple times, the last one will apply.
  #
  # One can use all long options that the program supports.
  # Run program with --help to get a list of available options and with
  # --print-defaults to see which it would actually understand and use.
  #
  # If you are new to MariaDB, check out https://mariadb.com/kb/en/basic-mariadb-articles/

  #
  # This group is read both by the client and the server
  # use it for options that affect everything
  #
  [client-server]
  # Port or socket location where to connect
  # port = 3306
  socket = /run/mysqld/mysqld.sock

  # Import all .cnf files from configuration directory

  !includedir /etc/mysql/mariadb.conf.d/
  !includedir /etc/mysql/conf.d/