                                # Es lo mismo que un configmap, solo que en la BBDD  interna de kubernetes
                                # Los datos se guardan encriptados... PERO ALLI !!! NO AQUI !!
kind:                 Secret    # Valores que se identifican con una clave y se pueden usar en los pods
                                # Para varias cosas, entre ellas para rellenar variables de entorno
apiVersion:           v1

metadata:
  name:               datos-secretos-mariadb

password:             cGFzc3dvcmQtc3VwZXItc2VjcmV0bw==           # Escribirlos en Base64 (Es un requisito)
password-root:        cGFzc3dvcmQtbcOhcy1zdXBlci1zZWNyZXRv       # Escribirlos en Base64 (Es un requisito)

# En muchas ocasiones no creamos objetos de tipo secret desde ficheros yaml
# Lo hacemos desde linea de comandos
# $ kubectl create secret generic datos-secretos-mariadb --from-literal=password='password-super-secreto' -n wordpress-desarrollo

---

kind:                 Secret 
apiVersion:           v1

metadata:
  name:               certificado_bbdd

mariadb.cert: |
  Lo que pongo aqui iría en Base64

# Pero también podría crearlo desde linea de comandos
# $ kubectl create secret generic certificado_bbdd --from-file=mariadb.cert=/home/ubuntu/environment/certificados/mariadb.cert -n wordpress-desarrollo
